### PR TITLE
LPS-61690 Save Custom Width & Height for Youtube Portlet

### PR DESCRIPTION
**Pull request by tylerwonglr**
Hey Jon! Check the work for the Youtube Portlet! I believe it can be even more optimized! Thanks!

### CODE REVIEW

**Comment by tylerwonglr** [comment]
Another solution would probably be to store the values into the actual <select> tag in the form of (value="[height]x[width]").  I thought that this solution required less code, but let me know if that sounds better.  Let me know what sounds good.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-plugins/pull/358

View just my changes: https://github.com/jonmak08/liferay-plugins/compare/tylerwonglr:9371ecc6ef...72aa31e81a
View total diff: https://github.com/jonmak08/liferay-plugins/compare/b5cdd21226...72aa31e81a

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/jbalsas/liferay-plugins/pull/6

View just my changes: https://github.com/jonmak08/liferay-plugins/compare/tylerwonglr:9371ecc6ef...72aa31e81a
View total diff: https://github.com/jonmak08/liferay-plugins/compare/b5cdd21226...72aa31e81a

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/natecavanaugh/liferay-plugins/pull/359

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Pull request closed without merging**
