### PR TITLE
LPS-55606

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @jgok and @dustinryerson,

I am still not able to reproduce this issue.  Can yo u explain to me in what scenario ```instance._initialRequest``` and ```response.initialRequest``` differ?  On every page reload, even with the notifications portlet enabled, ```instance._initialRequest``` still returns ```true``` only on the inital load of the poller.

Can you please explain this change?

**Comment by jgok** [comment]
@holatuwol, can you comment on the change?

**Comment by holatuwol** [comment]
@jonmak08, there are two scenarios where they differ.

In the first case, `response.initialRequest` is `false` while `instance.initialRequest` is `true`. This happens if the poller requests a non-initial update and the user switches pages before the update is received. In this case, after switching pages, the first response delivered by the server will be for the non-initial update, and then it will deliver a response for the initial update.

In the second case `response.initialRequest` is `true` while `instance.initialRequest` is `false`. This happens if the poller requests an initial update and the user switches pages before the update is received. In this case, the first response for the server will be an "initial" update (for the previous page) followed by another "initial" update (for the current page), which could cause the code to try to initialize twice.

**Comment by holatuwol** [comment]
In case it helps, I was able to reproduce the first case using breakpoints (as mentioned in https://github.com/jonmak08/liferay-portal/pull/1255), and the second case is hypothetically possible as well, but I have not tried to reproduce it.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-plugins/pull/344
View total diff: https://github.com/jonmak08/liferay-plugins/compare/58773c9d33...58c91e2169

**Pull request closed without merging**
